apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: static1
  name: static1
spec:
  selector:
    matchLabels:
      io.kompose.service: static1
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: static1
    spec:
      containers:
      - env:
        - name: port
          value: "5001"
        image: shcsdocker/static1
        name: static1
        ports:
        - containerPort: 5000
        resources: {}
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}
